/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cpsdna_jnidemo_CryptoNative */

#ifndef _Included_com_cpsdna_jnidemo_CryptoNative
#define _Included_com_cpsdna_jnidemo_CryptoNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cpsdna_jnidemo_CryptoNative
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cpsdna_jnidemo_CryptoNative_open
  (JNIEnv *, jobject);

/*
 * Class:     com_cpsdna_jnidemo_CryptoNative
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cpsdna_jnidemo_CryptoNative_close
  (JNIEnv *, jobject);

/*
 * Class:     com_cpsdna_jnidemo_CryptoNative
 * Method:    read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cpsdna_jnidemo_CryptoNative_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cpsdna_jnidemo_CryptoNative
 * Method:    write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_cpsdna_jnidemo_CryptoNative_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_cpsdna_jnidemo_CryptoNative
 * Method:    transfer
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cpsdna_jnidemo_CryptoNative_transfer
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_cpsdna_jnidemo_CryptoNative
 * Method:    hwReset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cpsdna_jnidemo_CryptoNative_hwReset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
